#############################################################################
# Makefile for building: Ruqola-android
# Generated by qmake (2.01a) (Qt 4.8.7) on: Thu Apr 13 00:09:45 2017
# Project:  Ruqola-android.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile Ruqola-android.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		src/ddpclient.cpp \
		src/messagemodel.cpp \
		src/notification.cpp \
		src/rocketchatbackend.cpp \
		src/roommodel.cpp \
		src/ruqola.cpp moc_ddpclient.cpp \
		moc_messagemodel.cpp \
		moc_notification.cpp \
		moc_rocketchatbackend.cpp \
		moc_roommodel.cpp \
		moc_ruqola.cpp \
		qrc_qml.cpp
OBJECTS       = main.o \
		ddpclient.o \
		messagemodel.o \
		notification.o \
		rocketchatbackend.o \
		roommodel.o \
		ruqola.o \
		moc_ddpclient.o \
		moc_messagemodel.o \
		moc_notification.o \
		moc_rocketchatbackend.o \
		moc_roommodel.o \
		moc_ruqola.o \
		qrc_qml.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Ruqola-android.pro
QMAKE_TARGET  = Ruqola-android
DESTDIR       = 
TARGET        = Ruqola-android

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Ruqola-android.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Ruqola-android.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Ruqola-android.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Ruqola-android1.0.0 || $(MKDIR) .tmp/Ruqola-android1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Ruqola-android1.0.0/ && $(COPY_FILE) --parents src/ddpclient.h src/messagemodel.h src/notification.h src/rocketchatbackend.h src/roommodel.h src/ruqola.h .tmp/Ruqola-android1.0.0/ && $(COPY_FILE) --parents qml.qrc .tmp/Ruqola-android1.0.0/ && $(COPY_FILE) --parents main.cpp src/ddpclient.cpp src/messagemodel.cpp src/notification.cpp src/rocketchatbackend.cpp src/roommodel.cpp src/ruqola.cpp .tmp/Ruqola-android1.0.0/ && (cd `dirname .tmp/Ruqola-android1.0.0` && $(TAR) Ruqola-android1.0.0.tar Ruqola-android1.0.0 && $(COMPRESS) Ruqola-android1.0.0.tar) && $(MOVE) `dirname .tmp/Ruqola-android1.0.0`/Ruqola-android1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Ruqola-android1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ddpclient.cpp moc_messagemodel.cpp moc_notification.cpp moc_rocketchatbackend.cpp moc_roommodel.cpp moc_ruqola.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ddpclient.cpp moc_messagemodel.cpp moc_notification.cpp moc_rocketchatbackend.cpp moc_roommodel.cpp moc_ruqola.cpp
moc_ddpclient.cpp: src/ddpclient.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/ddpclient.h -o moc_ddpclient.cpp

moc_messagemodel.cpp: src/messagemodel.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/messagemodel.h -o moc_messagemodel.cpp

moc_notification.cpp: src/notification.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/notification.h -o moc_notification.cpp

moc_rocketchatbackend.cpp: src/roommodel.h \
		src/rocketchatbackend.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/rocketchatbackend.h -o moc_rocketchatbackend.cpp

moc_roommodel.cpp: src/roommodel.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/roommodel.h -o moc_roommodel.cpp

moc_ruqola.cpp: src/ddpclient.h \
		src/roommodel.h \
		src/messagemodel.h \
		src/notification.h \
		src/ruqola.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/ruqola.h -o moc_ruqola.cpp

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		RoomModel.qml \
		systray.png \
		main.qml \
		Login.qml \
		Message.qml \
		JSONListModel.qml \
		jsonpath.js \
		RoomsView.qml \
		marked.js \
		RoomDelegate.qml \
		Desktop.qml
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp src/roommodel.h \
		src/rocketchatbackend.h \
		src/messagemodel.h \
		src/ruqola.h \
		src/ddpclient.h \
		src/notification.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ddpclient.o: src/ddpclient.cpp src/ddpclient.h \
		src/ruqola.h \
		src/roommodel.h \
		src/messagemodel.h \
		src/notification.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ddpclient.o src/ddpclient.cpp

messagemodel.o: src/messagemodel.cpp src/messagemodel.h \
		src/ruqola.h \
		src/ddpclient.h \
		src/roommodel.h \
		src/notification.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o messagemodel.o src/messagemodel.cpp

notification.o: src/notification.cpp src/ruqola.h \
		src/ddpclient.h \
		src/roommodel.h \
		src/messagemodel.h \
		src/notification.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o notification.o src/notification.cpp

rocketchatbackend.o: src/rocketchatbackend.cpp src/ruqola.h \
		src/ddpclient.h \
		src/roommodel.h \
		src/messagemodel.h \
		src/notification.h \
		src/rocketchatbackend.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rocketchatbackend.o src/rocketchatbackend.cpp

roommodel.o: src/roommodel.cpp src/roommodel.h \
		src/ruqola.h \
		src/ddpclient.h \
		src/messagemodel.h \
		src/notification.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o roommodel.o src/roommodel.cpp

ruqola.o: src/ruqola.cpp src/ruqola.h \
		src/ddpclient.h \
		src/roommodel.h \
		src/messagemodel.h \
		src/notification.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ruqola.o src/ruqola.cpp

moc_ddpclient.o: moc_ddpclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ddpclient.o moc_ddpclient.cpp

moc_messagemodel.o: moc_messagemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_messagemodel.o moc_messagemodel.cpp

moc_notification.o: moc_notification.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_notification.o moc_notification.cpp

moc_rocketchatbackend.o: moc_rocketchatbackend.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rocketchatbackend.o moc_rocketchatbackend.cpp

moc_roommodel.o: moc_roommodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_roommodel.o moc_roommodel.cpp

moc_ruqola.o: moc_ruqola.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ruqola.o moc_ruqola.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

